language: php

php:
    - 5.3
    - 5.4

script:
    - curl -s https://getcomposer.org/installer | php
    - php composer.phar install --dev --ansi
    - vendor/bin/behat --profile=travis @BehatViewerBundle